service: lucasklaassen

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  stage: production
  profile: personal
package:
  exclude:
    - docs/**
    - helpers/**
    - node_modules/**
    - test/**
resources:
  Resources:
    LucasKlaassenS3Bucket: ${file(config/s3Bucket.yml)}
    LucasKlaassenS3BucketPolicy: ${file(config/s3BucketPolicy.yml)}
    LucasKlaassenCloudFrontDistribution: ${file(config/cloudFront.yml)}
  Outputs: ${file(config/resourceOutputs.yml)}

plugins:
  - serverless-offline
  - serverless-single-page-app-plugin

custom:
  s3Bucket: lucasklaassen
  s3BucketDirectory: client/dist
  serverless-offline:
    babelOptions:
      presets: ["es2015"]